/**
 * Branded PDF generation used everywhere a list, sheet or receipt is
 * downloaded or printed: real styled PDFs (jsPDF + autotable) — never raw
 * HTML dumps or screen prints.
 */
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const PRIMARY: [number, number, number] = [76, 47, 209];
const INK: [number, number, number] = [29, 27, 51];

export interface BrandedTableOptions {
  title: string;
  subtitle?: string;
  schoolName?: string;
  columns: string[];
  rows: (string | number)[][];
  fileName: string;
  landscape?: boolean;
  /** Open the system print dialog instead of downloading. */
  print?: boolean;
  /** Extra footer line (e.g. totals). */
  footnote?: string;
}

function decorate(doc: jsPDF, options: BrandedTableOptions) {
  const width = doc.internal.pageSize.getWidth();
  // Header band
  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, width, 22, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(options.schoolName || "EduIgnite", 14, 9.5);
  doc.setFontSize(10);
  doc.text(options.title, 14, 16.5);
  if (options.subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(options.subtitle, width - 14, 16.5, { align: "right" });
  }
}

export function generateBrandedTablePdf(options: BrandedTableOptions) {
  const doc = new jsPDF({
    orientation: options.landscape ? "landscape" : "portrait",
    unit: "mm",
    format: "a4",
  });

  decorate(doc, options);

  autoTable(doc, {
    startY: 27,
    head: [options.columns],
    body: options.rows.map((row) => row.map((cell) => String(cell ?? ""))),
    styles: { font: "helvetica", fontSize: 8.5, textColor: INK, cellPadding: 2.2 },
    headStyles: { fillColor: PRIMARY, textColor: [255, 255, 255], fontStyle: "bold", fontSize: 9 },
    alternateRowStyles: { fillColor: [243, 240, 252] },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      if (data.pageNumber > 1) decorate(doc, options);
      const height = doc.internal.pageSize.getHeight();
      const width = doc.internal.pageSize.getWidth();
      doc.setFontSize(7.5);
      doc.setTextColor(130, 130, 150);
      doc.setFont("helvetica", "normal");
      doc.text(
        `Generated by EduIgnite • ${new Date().toLocaleString()}`,
        14,
        height - 7
      );
      doc.text(`Page ${data.pageNumber}`, width - 14, height - 7, { align: "right" });
    },
  });

  if (options.footnote) {
    const finalY = (doc as any).lastAutoTable?.finalY ?? 30;
    doc.setFontSize(9);
    doc.setTextColor(...INK);
    doc.setFont("helvetica", "bold");
    doc.text(options.footnote, 14, Math.min(finalY + 8, doc.internal.pageSize.getHeight() - 12));
  }

  if (options.print) {
    doc.autoPrint();
    const url = doc.output("bloburl");
    window.open(url, "_blank");
  } else {
    doc.save(options.fileName.endsWith(".pdf") ? options.fileName : `${options.fileName}.pdf`);
  }
}

export interface ReceiptOptions {
  schoolName: string;
  title: string;
  lines: [string, string][];
  reference?: string;
  fileName: string;
  print?: boolean;
}

/** A5 payment receipt with the EduIgnite band and a details grid. */
export function generateReceiptPdf(options: ReceiptOptions) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a5" });
  const width = doc.internal.pageSize.getWidth();

  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, width, 26, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(options.schoolName, width / 2, 11, { align: "center" });
  doc.setFontSize(10);
  doc.text(options.title, width / 2, 19, { align: "center" });

  autoTable(doc, {
    startY: 34,
    body: options.lines,
    theme: "plain",
    styles: { font: "helvetica", fontSize: 10, textColor: INK, cellPadding: 3 },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 48, textColor: [110, 106, 138] },
      1: { fontStyle: "bold" },
    },
    margin: { left: 12, right: 12 },
    didParseCell: (data) => {
      if (data.row.index % 2 === 0) data.cell.styles.fillColor = [243, 240, 252];
    },
  });

  const y = (doc as any).lastAutoTable?.finalY ?? 60;
  if (options.reference) {
    doc.setFontSize(8.5);
    doc.setTextColor(110, 106, 138);
    doc.text(`Reference: ${options.reference}`, 12, y + 8);
  }
  doc.setFontSize(8);
  doc.setTextColor(130, 130, 150);
  doc.text(
    `Generated by EduIgnite • ${new Date().toLocaleString()}`,
    width / 2,
    doc.internal.pageSize.getHeight() - 8,
    { align: "center" }
  );

  if (options.print) {
    doc.autoPrint();
    window.open(doc.output("bloburl"), "_blank");
  } else {
    doc.save(options.fileName.endsWith(".pdf") ? options.fileName : `${options.fileName}.pdf`);
  }
}
