/**
 * Branded PDF generation used everywhere a list, sheet or receipt is
 * downloaded or printed: real styled PDFs (jsPDF + autotable) — never raw
 * HTML dumps or screen prints.
 */
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { isNativeApp, saveToEduignite } from "@/lib/native-download";

/**
 * Save a jsPDF document. On the native app the browser download does nothing,
 * so we write the PDF into the device Documents/eduignite folder instead.
 */
function savePdfDoc(doc: jsPDF, rawName: string) {
  const fileName = rawName.endsWith(".pdf") ? rawName : `${rawName}.pdf`;
  if (isNativeApp()) {
    try {
      const base64 = doc.output("datauristring").split(",")[1] || "";
      void saveToEduignite({ fileName, base64, mimeType: "application/pdf" });
      return;
    } catch {
      /* fall through to browser save */
    }
  }
  doc.save(fileName);
}

const PRIMARY: [number, number, number] = [76, 47, 209];
const INK: [number, number, number] = [29, 27, 51];

export interface BrandedTableOptions {
  title: string;
  subtitle?: string;
  schoolName?: string;
  columns: string[];
  rows: (string | number)[][];
  fileName: string;
  landscape?: boolean;
  /** Open the system print dialog instead of downloading. */
  print?: boolean;
  /** Extra footer line (e.g. totals). */
  footnote?: string;
}

function decorate(doc: jsPDF, options: BrandedTableOptions) {
  const width = doc.internal.pageSize.getWidth();
  // Header band
  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, width, 22, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(options.schoolName || "EduIgnite", 14, 9.5);
  doc.setFontSize(10);
  doc.text(options.title, 14, 16.5);
  if (options.subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(options.subtitle, width - 14, 16.5, { align: "right" });
  }
}

export function generateBrandedTablePdf(options: BrandedTableOptions) {
  const doc = new jsPDF({
    orientation: options.landscape ? "landscape" : "portrait",
    unit: "mm",
    format: "a4",
  });

  decorate(doc, options);

  autoTable(doc, {
    startY: 27,
    head: [options.columns],
    body: options.rows.map((row) => row.map((cell) => String(cell ?? ""))),
    styles: { font: "helvetica", fontSize: 8.5, textColor: INK, cellPadding: 2.2 },
    headStyles: { fillColor: PRIMARY, textColor: [255, 255, 255], fontStyle: "bold", fontSize: 9 },
    alternateRowStyles: { fillColor: [243, 240, 252] },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      if (data.pageNumber > 1) decorate(doc, options);
      const height = doc.internal.pageSize.getHeight();
      const width = doc.internal.pageSize.getWidth();
      doc.setFontSize(7.5);
      doc.setTextColor(130, 130, 150);
      doc.setFont("helvetica", "normal");
      doc.text(
        `Generated by EduIgnite • ${new Date().toLocaleString()}`,
        14,
        height - 7
      );
      doc.text(`Page ${data.pageNumber}`, width - 14, height - 7, { align: "right" });
    },
  });

  if (options.footnote) {
    const finalY = (doc as any).lastAutoTable?.finalY ?? 30;
    doc.setFontSize(9);
    doc.setTextColor(...INK);
    doc.setFont("helvetica", "bold");
    doc.text(options.footnote, 14, Math.min(finalY + 8, doc.internal.pageSize.getHeight() - 12));
  }

  if (options.print) {
    doc.autoPrint();
    const url = doc.output("bloburl");
    window.open(url, "_blank");
  } else {
    savePdfDoc(doc, options.fileName);
  }
}

// ── Report cards ────────────────────────────────────────────────────────────
// Render one report card per A4 page (fit-to-page, ordered, no page numbers) so
// a class batch can be printed individually, one student per sheet.
function drawReportCard(doc: jsPDF, card: any, fallbackSchool?: string, fallbackTitle?: string) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const student = card?.student || {};
  const school = card?.school || {};
  const seq = card?.sequence || {};

  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, W, 24, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(String(school.name || fallbackSchool || "EduIgnite"), W / 2, 10, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const period = seq.name
    ? `${seq.name} · Term ${seq.term || ""} · ${seq.academic_year || ""}`
    : (fallbackTitle || "Report Card");
  doc.text(`Report Card — ${period}`, W / 2, 17, { align: "center" });

  doc.setTextColor(...INK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(String(student.name || ""), 14, 33);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(`Class: ${student.class_name || student.class || ""}`, 14, 39);
  doc.text(`Matricule: ${student.matricule || ""}`, W - 14, 33, { align: "right" });
  doc.text(`Adm. No: ${student.admission_number || ""}`, W - 14, 39, { align: "right" });

  autoTable(doc, {
    startY: 44,
    head: [["Subject", "Coef", "/20", "Grade", "Total", "Teacher", "Remark"]],
    body: (card?.grades || []).map((g: any) => [
      String(g.subject_name ?? ""),
      String(g.coefficient ?? ""),
      String(g.score ?? ""),
      String(g.grade_letter ?? ""),
      String(g.total ?? ""),
      String(g.teacher_name ?? ""),
      String(g.comment ?? ""),
    ]),
    styles: { font: "helvetica", fontSize: 8, textColor: INK, cellPadding: 1.6 },
    headStyles: { fillColor: PRIMARY, textColor: [255, 255, 255], fontStyle: "bold", fontSize: 8.5 },
    alternateRowStyles: { fillColor: [243, 240, 252] },
    columnStyles: {
      1: { halign: "center" }, 2: { halign: "center" }, 3: { halign: "center" }, 4: { halign: "center" },
    },
    margin: { left: 14, right: 14 },
    theme: "grid",
  });

  const afterY = (doc as any).lastAutoTable?.finalY ?? 60;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...INK);
  const rankTxt = card?.rank != null ? `${card.rank}${card?.total_students ? ` / ${card.total_students}` : ""}` : "—";
  doc.text(
    `Average: ${card?.average ?? "—"}/20     Rank: ${rankTxt}     Status: ${card?.promotion_status || ""}`,
    14,
    Math.min(afterY + 8, H - 20),
  );

  if (card?.qr_code) {
    try {
      doc.addImage(card.qr_code, "PNG", W - 34, Math.min(afterY + 2, H - 30), 20, 20);
      doc.setFontSize(6.5);
      doc.setTextColor(130, 130, 150);
      doc.setFont("helvetica", "normal");
      doc.text("Scan to verify", W - 24, Math.min(afterY + 24, H - 8), { align: "center" });
    } catch {
      /* qr embed failed — skip */
    }
  }

  doc.setFontSize(8);
  doc.setTextColor(130, 130, 150);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by EduIgnite · official report card", 14, H - 8);
}

export interface ReportCardsPdfOptions {
  schoolName?: string;
  title?: string;
  fileName: string;
  print?: boolean;
}

export function generateReportCardsPdf(cards: any[], options: ReportCardsPdfOptions) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const list = (cards || []).filter(Boolean);
  if (list.length === 0) return;
  list.forEach((card, index) => {
    if (index > 0) doc.addPage();
    drawReportCard(doc, card, options.schoolName, options.title);
  });
  if (options.print) {
    doc.autoPrint();
    window.open(doc.output("bloburl"), "_blank");
  } else {
    savePdfDoc(doc, options.fileName);
  }
}

export interface ReceiptOptions {
  schoolName: string;
  title: string;
  lines: [string, string][];
  reference?: string;
  fileName: string;
  print?: boolean;
}

/** A5 payment receipt with the EduIgnite band and a details grid. */
export function generateReceiptPdf(options: ReceiptOptions) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a5" });
  const width = doc.internal.pageSize.getWidth();

  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, width, 26, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(options.schoolName, width / 2, 11, { align: "center" });
  doc.setFontSize(10);
  doc.text(options.title, width / 2, 19, { align: "center" });

  autoTable(doc, {
    startY: 34,
    body: options.lines,
    theme: "plain",
    styles: { font: "helvetica", fontSize: 10, textColor: INK, cellPadding: 3 },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 48, textColor: [110, 106, 138] },
      1: { fontStyle: "bold" },
    },
    margin: { left: 12, right: 12 },
    didParseCell: (data) => {
      if (data.row.index % 2 === 0) data.cell.styles.fillColor = [243, 240, 252];
    },
  });

  const y = (doc as any).lastAutoTable?.finalY ?? 60;
  if (options.reference) {
    doc.setFontSize(8.5);
    doc.setTextColor(110, 106, 138);
    doc.text(`Reference: ${options.reference}`, 12, y + 8);
  }
  doc.setFontSize(8);
  doc.setTextColor(130, 130, 150);
  doc.text(
    `Generated by EduIgnite • ${new Date().toLocaleString()}`,
    width / 2,
    doc.internal.pageSize.getHeight() - 8,
    { align: "center" }
  );

  if (options.print) {
    doc.autoPrint();
    window.open(doc.output("bloburl"), "_blank");
  } else {
    savePdfDoc(doc, options.fileName);
  }
}
